trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: firstjob
    steps:
    - bash: echo Build firstjob
  - job: secondjob
    steps:
    - bash: echo Build secondjob
    - bash: echo $(PipelineLevelVariable)

- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployjob
    steps:
    - bash: echo $(environment)Deployjob

- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build
  jobs:
  - job: QADeployjob
    steps:
    - bash: echo $(environment)Deployjob

- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployjob
    steps:
    - bash: echo $(environment)Deployjob