trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: firstjob
    steps:
    - bash: echo Build firstjob
  - job: secondjob
    steps:
    - bash: echo Build secondjob

- stage: DevDeploy
  dependOn: Build
  jobs:
  - job: DevDeployjob
    steps:
    - bash: echo DevDeployjob

- stage: QADeploy
  dependOn: Build
  jobs:
  - job: QADeployjob
    steps:
    - bash: echo QADeployjob

- stage: ProdDeploy
  dependOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployjob
    steps:
    - bash: echo QADeployjob